spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/network_server
    username: root
    password: admin
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8080

reaktor:
  cronComputerOn: 5_000
  cronComputerOnDifference: 7_000
