spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/network_server
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8080
springdoc.api-docs.path: /api-docs
reaktor:
  cronComputerOn: 5_000
  cronComputerOnDifference: 7_000
